"""Can the Q-measure jump parameters be recovered, and at which tenors?

Under Girsanov an equivalent change of measure cannot touch a diffusion
coefficient, so sigma_Q = sigma_P and only the jump compensator moves. That
leaves four parameters to calibrate on the index surface - pprob, lamb, eta1,
eta2 - and this asks the same question the P-side harness asked: put known
values in, price a surface, calibrate it back, and see what returns.

The answer is expected to depend on TENOR. A jump shows up in an option price
as excess skew and kurtosis, and over a long horizon the sum of many jumps
goes Gaussian, so the smile flattens and the four parameters stop being
separately visible. Short tenors should pin them; long tenors should not. The
tenor ladder is what locates the crossover.

    python poc/recover_q_jumps.py
    PPROB=0.30 LAMB=8 ETA1=18 ETA2=9 SIGMA=0.15 python poc/recover_q_jumps.py
    NSTRIKES=31 NOISE=0.002 python poc/recover_q_jumps.py
    TENORS=1M,1Y,7Y python poc/recover_q_jumps.py     # a subset, to go fast

THE TRUTHS ARE DELIBERATELY NOT x0. Production starts SLSQP at
(0.2, 5, 22, 7). A truth sitting on the starting point is recovered by an
optimizer that never moves, which measures nothing - the same trap that made
an earlier P-side coverage run vacuous. The defaults below sit well away from
it, and changing them is how you check that the answer is not about one
particular point.

THE SYNTHETIC MARKET COMES FROM model_vol() ITSELF, evaluated at the true
parameters. That is on purpose: the calibrator then sees a surface generated
by exactly the function it evaluates, so anything that fails to come back is
identification or the optimizer, never a pricing or quoting convention that
differs between the two sides.
"""
import os
import sys
from pathlib import Path

import numpy as np
from scipy.optimize import minimize
from scipy.stats import norm

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from Library.SkewCalibrationKimYi2025 import KimYiSkewCalibrationSystematic  # noqa: E402

TENORS = [("1D", 1 / 365), ("7D", 7 / 365), ("14D", 14 / 365),
          ("1M", 1 / 12), ("2M", 2 / 12), ("3M", 3 / 12), ("6M", 6 / 12),
          ("9M", 9 / 12), ("1Y", 1.0), ("1.5Y", 1.5), ("2Y", 2.0),
          ("3Y", 3.0), ("4Y", 4.0), ("5Y", 5.0), ("6Y", 6.0), ("7Y", 7.0)]

# Production's SLSQP start and bounds, copied so the harness tests what the
# script actually runs rather than a friendlier configuration.
X0 = np.array([.2, 5., 22., 7.])
BOUNDS = [(0., 1.), (1e-4, None), (1.5, None), (0.5, None)]
NAMES = ["pprob", "lamb", "eta1", "eta2"]

# SLSQP takes one finite-difference step and one convergence tolerance for
# every coordinate, so a search where pprob is 0.2 and eta1 is 22 - two orders
# of magnitude apart - is effectively isotropic in the wrong metric. It stops
# early: on a NOISELESS surface generated by the model itself, where the
# objective at the truth is exactly 0, production's settings halt at 3.6e-06
# and 35% away from the answer. Dividing through by X0 - a scale the
# calibrator already has, so nothing about the truth leaks in - recovers the
# truth to six figures. Both are reported below; the gap is the cost of the
# current script's parameterisation, not a property of the model.
SCALE = X0.copy()


def fit_raw(fit):
    r = minimize(fit.target, x0=X0, method="SLSQP", bounds=BOUNDS,
                 tol=1e-8, options={"maxiter": 10000})
    return np.asarray(r.x, dtype=float)


def fit_scaled(fit):
    bnds = [(lo / s, None if hi is None else hi / s)
            for (lo, hi), s in zip(BOUNDS, SCALE)]
    r = minimize(lambda u: fit.target(u * SCALE), x0=X0 / SCALE,
                 method="SLSQP", bounds=bnds, tol=1e-12,
                 options={"maxiter": 10000})
    return np.asarray(r.x, dtype=float) * SCALE


def total_vol(sigma, p, lam, eta1, eta2):
    """sqrt of diffusive plus jump variance per year - sets the strike range."""
    jump = lam * (2 * p / eta1 ** 2 + 2 * (1 - p) / eta2 ** 2)
    return float(np.sqrt(sigma ** 2 + jump))


def build(T, x_true, sigma, n, s0, r, q, tot_vol, rng=None, noise=0.0):
    """A fitter whose 'market' is this model priced at x_true."""
    width = min(3.0 * tot_vol * np.sqrt(T), 1.0)      # +-3 sd, capped at e^1
    strikes = s0 * np.exp(np.linspace(-width, width, n))
    fwd = s0 * np.exp((r - q) * T)
    is_call = strikes > fwd                            # OTM quoting convention

    col = lambda v: np.full(n, float(v))
    fit = KimYiSkewCalibrationSystematic(
        mkt_imp_vol=np.zeros(n), und_price=col(s0), und_strike=strikes,
        risk_free_rate=col(r), dividend_yield=col(q), time_to_expiry=col(T),
        is_call_option=is_call,
        option_weights=np.ones((n, 1)) / n, sigma=np.array(sigma))

    iv = np.asarray(fit.model_vol(x_true)).reshape(-1)
    if not np.all(np.isfinite(iv)):
        return None

    # model_vol stacks PUTS FIRST, then calls, so everything compared against
    # it - the market vector and the weights - has to be in that same order.
    order = np.concatenate([np.flatnonzero(~is_call), np.flatnonzero(is_call)])
    k_ord, t_ord = strikes[order], float(T)
    d1 = ((np.log(s0 / k_ord) + (r - q + 0.5 * iv ** 2) * t_ord)
          / (iv * np.sqrt(t_ord)))
    vega = s0 * np.exp(-q * t_ord) * norm.pdf(d1) * np.sqrt(t_ord)

    mkt = iv if noise <= 0 else iv + rng.normal(0, noise, iv.shape)
    fit.mkt_imp_vol = mkt
    fit.option_weights = (vega / vega.sum()).reshape((-1, 1))
    return fit, strikes, iv, order


def smile_skew(strikes, iv, order, s0):
    """Down-wing IV minus up-wing IV, in vol points, across the grid's own ends.

    Fixed moneyness (90 vs 110) is useless here: a 1D grid spans barely +-2%,
    so it never reaches either. The grid is +-3 sd at every tenor, so its
    endpoints are the comparable measure - and watching this number decay is
    watching the jumps stop being visible in the surface.
    """
    m = strikes[order] / s0
    lo, hi = int(np.argmin(m)), int(np.argmax(m))
    return float(iv[lo] - iv[hi]) * 100


def main():
    env = lambda k, d: float(os.environ.get(k, d))
    sigma = env("SIGMA", 0.15)
    x_true = np.array([env("PPROB", 0.30), env("LAMB", 8.0),
                       env("ETA1", 18.0), env("ETA2", 9.0)])
    n = int(env("NSTRIKES", 21))
    noise = env("NOISE", 0.0)
    s0, r, q = env("SPOT", 100.0), env("RATE", 0.04), env("DIVY", 0.015)
    rng = np.random.default_rng(int(env("SEED", 20240114)))

    tot = total_vol(sigma, *x_true)
    print("sigma %.4f (held at its P value), true jump parameters %s"
          % (sigma, dict(zip(NAMES, x_true))))
    print("total Q vol %.1f%%/yr, %d strikes per tenor, SLSQP from %s%s\n"
          % (100 * tot, n, list(X0), "" if noise <= 0
             else ", IV noise %.1f vol pt" % (100 * noise)))

    print("  %-6s %8s %8s %8s %8s %9s %9s %8s"
          % ("tenor", "pprob", "lamb", "eta1", "eta2", "err", "err(raw)", "wing"))
    print("  %-6s %8.3f %8.3f %8.3f %8.3f %9s %9s %8s\n"
          % ("TRUE", x_true[0], x_true[1], x_true[2], x_true[3], "", "", ""))

    want = os.environ.get("TENORS")
    ladder = ([t for t in TENORS if t[0] in want.split(",")] if want else TENORS)

    stack = []
    for label, T in ladder:
        built = build(T, x_true, sigma, n, s0, r, q, tot, rng, noise)
        if built is None:
            print("  %-6s   (IV inversion failed at the true parameters)" % label)
            continue
        fit, strikes, iv, order = built
        stack.append(fit)
        xh, xr = fit_scaled(fit), fit_raw(fit)
        rel = lambda v: 100 * np.max(np.abs(v - x_true) / x_true)
        print("  %-6s %8.3f %8.3f %8.3f %8.3f %8.1f%% %8.0f%% %8.2f"
              % (label, xh[0], xh[1], xh[2], xh[3], rel(xh), rel(xr),
                 smile_skew(strikes, iv, order, s0)))

    if len(stack) > 1:
        class _Joint:
            target = staticmethod(
                lambda x: sum(float(f.target(x)) for f in stack))
        xh = fit_scaled(_Joint)
        print("\n  %-6s %8.3f %8.3f %8.3f %8.3f %8.1f%%   (all %d tenors "
              "at once)"
              % ("JOINT", xh[0], xh[1], xh[2], xh[3],
                 100 * np.max(np.abs(xh - x_true) / x_true), len(stack)))


if __name__ == "__main__":
    main()
